// Generated by CoffeeScript 1.3.3
var MyApp;

MyApp = (function() {

  function MyApp() {
    this.xhr = new XMLHttpRequest();
    this.xhr.onreadystatechange = function(e) {
      var data, html, item, template;
      this.mainList = document.querySelector("#main");
      if (this.readyState === this.DONE) {
        data = JSON.parse(this.response);
        data = data.photos.photo;
        console.log(data);
        html = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = data.length; _i < _len; _i++) {
            item = data[_i];
            template = "<li><img src=\"{SRC}\" /></li>";
            _results.push(template.replace("{SRC}", item.url_m));
          }
          return _results;
        })();
        this.mainList.innerHTML = "";
        return this.mainList.innerHTML = html.join("\n");
      }
    };
  }

  MyApp.prototype.search = function(text) {
    var apikey, url;
    url = "http://api.flickr.com/services/rest/?method=flickr.photos.search&extras=url_m&per_page=20&format=json&nojsoncallback=1&safe_search=1";
    apikey = "6ecfcd8d4a3b8a04da6093733db989a2";
    url += '&api_key=' + apikey;
    url += "&text=" + text;
    url = encodeURI(url);
    this.xhr.open("GET", url, true);
    return this.xhr.send();
  };

  return MyApp;

})();
